# Generated by Django 4.2.21 on 2025-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
