# Generated by Django 4.2.21 on 2025-05-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill_alter_userprofile_education_and_more'),
        ('jobs', '0004_alter_jobapplication_applicant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant')},
        ),
    ]
