# Generated by Django 4.2.21 on 2025-05-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_posted_at_job_applications_job_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('HY', 'Hybrid'), ('RM', 'Remote')], max_length=2, null=True),
        ),
    ]
