# Generated by Django 4.2.21 on 2025-05-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_options_remove_conversation_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation'),
        ),
    ]
